### ISSUE TITLE
/photo <N> | Question

### ISSUE THREAD

**Issue by jeffscrum** [Romancha/photo-moments-telegram-bot#1]
Hi,
How can I disable the command, sending by specifying a number? It causes false triggering
I only want to keep "/photo </N>".
Thanks

-- RU --
Добрый день,
Подскажите пожалуйста, как я могу отключить команду, чтобы бот не отправлял фото, если указана просто цифра?
Мне нужно оставить только команду /photo <N>, в избежание случайных срабатываний
Спасибо

**Comment by Romancha** [comment]
Hi!
Check new 1.2.0 version, i add this feature for you.
Just set env `FM_SEND_PHOTOS_BY_NUMBER` to `false`

**Comment by jeffscrum** [comment]
Thanks a lot
